import 'all_imports.dart';

getRoutes() {
  return {
    // MyHomePage.route: (context) => MyHomepage(),
    MyHomePage.route: (context) => MyHomePage(),
    SearchBar.route: (context) => SearchBar(),
    CellsLesson.route: (context) => CellsLesson(),
    TissuesLesson.route: (context) => TissuesLesson(),
    CellCycleLesson.route: (context) => CellCycleLesson(),
    ChromosomalLesson.route: (context) => ChromosomalLesson(),
    CellMembraneLesson.route: (context) => CellMembraneLesson(),
    MovementMaterialsLesson.route: (context) => MovementMaterialsLesson(),
    EnzymesLesson.route: (context) => EnzymesLesson(),
    Cells1.route: (context) => Cells1(),
    Cells2.route: (context) => Cells2(),
    Cells3.route: (context) => Cells3(),
    Cells4.route: (context) => Cells4(),
    Cells5.route: (context) => Cells5(),
    Tissues1.route: (context) => Tissues1(),
    Tissues2.route: (context) => Tissues2(),
    Tissues3.route: (context) => Tissues3(),
    Tissues4.route: (context) => Tissues4(),
    Tissues5.route: (context) => Tissues5(),
    Tissues6.route: (context) => Tissues6(),
    Tissues7.route: (context) => Tissues7(),
    CellCycle1.route: (context) => CellCycle1(),
    CellCycle2.route: (context) => CellCycle2(),
    CellCycle3.route: (context) => CellCycle3(),
    CellCycle4.route: (context) => CellCycle4(),
    Chromosomal1.route: (context) => Chromosomal1(),
    Chromosomal2.route: (context) => Chromosomal2(),
    CellMembrane1.route: (context) => CellMembrane1(),
    CellMembrane2.route: (context) => CellMembrane2(),
    CellMembrane3.route: (context) => CellMembrane3(),
    MovementMaterials1.route: (context) => MovementMaterials1(),
    MovementMaterials2.route: (context) => MovementMaterials2(),
    MovementMaterials3.route: (context) => MovementMaterials3(),
    MovementMaterials4.route: (context) => MovementMaterials4(),
    MovementMaterials5.route: (context) => MovementMaterials5(),
    Enzymes1.route: (context) => Enzymes1(),
    Enzymes2.route: (context) => Enzymes2(),
    Enzymes3.route: (context) => Enzymes3(),
  };
}

// class AllRoutes {
//   String routes;

//   AllRoutes({this.routes})
// }

// List<String> routes = [
//   MyHomePage.route,
//     Cells1.route,
//     Cells2.route,
//     Cells3.route,
//     Cells4.route,
//     Cells5.route,
//     Cells6.route,
//     Tissues1.route,
//     Tissues2.route,
//     Tissues3.route,
//     Tissues4.route,
//     Tissues5.route,
//     Tissues6.route,
//     Tissues7.route,
//     CellCycle1.route,
//     CellCycle2.route,
//     CellCycle3.route,
//     CellCycle4.route,
//     CellCycle5.route,
//     CellCycle6.route,
//     CellCycle7.route,
//     CellCycle8.route,
//     CellCycle9.route,
//     CellCycle10.route,
//     CellCycle11.route,
//     Chromosomal1.route,
//     Chromosomal2.route,
//     CellMembrane1.route,
//     CellMembrane2.route,
//     CellMembrane3.route,
//     MovementMaterials1.route,
//     MovementMaterials2.route,
//     MovementMaterials3.route,
//     MovementMaterials4.route,
//     MovementMaterials5.route,
//     MovementMaterials6.route,
//     MovementMaterials7.route,
//     MovementMaterials8.route,
//     MovementMaterials9.route,
//     MovementMaterials10.route,
//     Enzymes1.route,
//     Enzymes2.route,
//     Enzymes3.route,
//     Enzymes4.route,
// ];
